namespace Nitrogen.GameVariants.Megalo
{
	public enum ParameterType
	{
		None,

		Boolean,
		Float,
		UInt5,
		Byte,
		Int32,

		GenericReference,
		PlayerReference,
		ObjectReference,
		TeamReference,
		IntegerReference,
		TimerReference,
		TargetReference,
		StringReference,
		StringReferenceOneToken,
		StringReferenceTwoTokens,
		StringReferenceThreeTokens,

		VirtualTrigger,
		Shape,
		Meter,
		EntityFilter,
		WaypointIcon,

		ComparisonType,
		PlayerKillerTypeFlags,
		TeamDisposition,
		MultiplayerObjectType,
		ObjectFilter,
		Incident,
		OperationType,
		String,
		ObjectSpawnFlags,
		Coordinates3d,
		WaypointPriority,
		ObjectTimer,
		PlayerTraits,
		FireteamFilter,
		Sound,
		TimerRate,
		Trigger,
		PlayerModes,
		WeaponPickupMode,
		Widget,
		WidgetIcon,
		HudPosition,
		VariantIcon,
		RequisitionPalette,
		GrenadeType,
		LoadoutPalette,
		DeviceAnimation,
		GiveWeaponMode,
		DropWeaponMode,
		ObjectPlayer,
		Button,
		Medal,
		PowerupType,
	}
}
