/*
 *   Nitrogen - Halo Content API
 *   Copyright (c) 2013 Matt Saville and Aaron Dierking
 * 
 *   This file is part of Nitrogen.
 *
 *   Nitrogen is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   Nitrogen is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with Nitrogen.  If not, see <http://www.gnu.org/licenses/>.
 */

using Nitrogen.Core.IO;
using System;
using System.Text;

namespace Nitrogen.Core.Blf
{
    internal class BlobHeader
        : Chunk
    {
        private string fileSummary;
        private short byteOrderMark;

        internal BlobHeader()
            : base("_blf", 1, 48)
        {
            this.fileSummary = "Generated by Nitrogen";
            this.byteOrderMark = -2;
        }

        protected override ChunkFlags Flags { get { return ChunkFlags.IsHeader; } }

        protected override void SerializeEndianStreamData(IO.EndianStream s)
        {
            s.Stream(ref byteOrderMark);
            s.StreamBlock(32, () => s.Stream(ref this.fileSummary, Encoding.ASCII));

            if (this.byteOrderMark != -2)
                s.SetEndianness(ByteOrder.LittleEndian);
        }
    }
}
